### ISSUE TITLE
Table definition

### ISSUE THREAD

**Issue by kbrock** [franckverrot/holycorn#7]
This is fun stuff.

For the following definition:

```sql
DROP EXTENSION holycorn CASCADE;
CREATE EXTENSION holycorn;
CREATE SERVER holycorn_server FOREIGN DATA WRAPPER holycorn;
CREATE FOREIGN TABLE holytable (some_date timestampz) \
  SERVER holycorn_server
  OPTIONS (wrapper_path '/tmp/source.rb');
```

Is there a way for the class defined in `/tmp/source.rb` to know the schema (`some_date timestampz`) of the table?

I'm under the impression that only the `OPTIONS` are passed (as a hash) to `initialize`.

thanks

**Comment by kbrock** [comment]
closing. Think this would incur too much overhead as `initialize(OPTIONS)` is called for every query. Most (all?) of the time the ruby will not want to dynamically change.

`OPTIONS` can be used to pass extra parameters as needed.

**Comment by franckverrot** [comment]
This is actually a very good question, and I've been asked many times so here's an "official" answer 😄 

PG provides `IMPORT FOREIGN SCHEMA` that is essentially a way for it to "ask" foreign servers for their table definitions.

Most `holycorn-pro` users felt the need to get it, and also wanted to encapsulate more information in user mappings. I got both `IMPORT FOREIGN SCHEMA` and `USER MAPPING`s supported there.

Any cool usage of `holycorn` on your side? 😉

**Comment by kbrock** [comment]
Thanks Frank.

I keep running into yaml in a text column and wanting a way to parse in Postgres. So something like pl/ruby (or lua or js - but ruby would be the best) to allow queries to extract a column, change it or join.

Your video on the three possible options was great. I do wonder what pl/mruby would be like. But the fdw bridge seems to buy a lot in its own right. 

Didn't get the chance to even get holycorn up and running yet. Little intimidated.
Also, not sure it would help us without where or joins.

Thanks for the great video, project, and I'll share what I find.

**Comment by franckverrot** [comment]
Long overdue but finally decided to open source `IMPORT FOREIGN SCHEMA` [(code)] (hacktoberfest is great ahah).

Anyways, you can do something like this now:

```sql
IMPORT FOREIGN SCHEMA holycorn_schema
FROM SERVER holycorn_server
INTO holycorn_tables
OPTIONS ( wrapper_class '...'
        , foo 'bar'
        , baz 'bat'
        );
```

and you'll end up with `foo` and `baz` passed within a hash to the `#import_schema` method of your wrapper class.

If you were dynamically generating mappings before, then you could pass some information from that SQL statement to the wrapper, and decide what to do in Ruby-land code.

Hope this helps.


[(code)]: https://github.com/franckverrot/holycorn/pull/11/commits/aacb7b098a8aeb164722901e107899f89395dedf
